// Code generated by "stringer -type=Space -linecomment"; DO NOT EDIT.

package day07

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EMPTY-0]
	_ = x[SOURCE-1]
	_ = x[SPLITTER-2]
	_ = x[BEAM-3]
}

const _Space_name = ".S^|"

var _Space_index = [...]uint8{0, 1, 2, 3, 4}

func (i Space) String() string {
	if i < 0 || i >= Space(len(_Space_index)-1) {
		return "Space(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Space_name[_Space_index[i]:_Space_index[i+1]]
}
